export const SHEETS = {
  readme: '00_Read Me',
  contentCalendar: '01_Content Calendar',
  eventsMatches: '02_Events Matches',
  playersContent: '03_Players Content',
  assetsLibrary: '04_Assets Library',
  storylines: '05_Storylines',
  templates: '06_Templates',
  publishedArchive: '07_Published Archive',
  partnersScouting: '08_Partners Scouting',
  systemLogs: '09_System Logs',
  dedup: '10_Dedup',
  feedbackRules: '11_Feedback Rules',
  projectContext: '12_Project Context',
  brandRulesMemory: '13_Brand Rules',
  botMemory: '14_Bot Memory',
  approvedExamples: '15_Approved Examples',
  rejectedExamples: '16_Rejected Examples',
  visualPrompts: '17_Visual Prompts',
  matchLogSources: '18_Match Log Sources',
  playerMasterSnapshot: '19_Player Master Snapshot',
  matchLogSnapshot: '20_Match Log Snapshot',
  publicationSchedule: '21_Publication Schedule',
  mediaSuggestions: '22_Media Suggestions',
  strategicBriefs: '23_Strategic SMM Briefs',
  lifecycleRules: '24_Event Lifecycle Rules',
  userActionTasks: '25_User Action Tasks',
  sponsorIntegrations: '26_Sponsor Integrations',
  ecosystemProducts: '27_Ecosystem Products',
  contentMixAudit: '28_Content Mix Audit',
  generatedImages: '29_Generated Images',
  modelConfig: '30_Model Config',
  approvalQueue: '31_Approval Queue',
  reminders: '32_Reminders',
  followupLog: '33_Follow-up Log',
  telegramMessageLinks: '34_Telegram Message Links',
  stylePack: '35_Style Pack',
  referenceAssets: '36_Reference Assets',
  assetUsageHistory: '37_Asset Usage History',
  campaignState: '38_Campaign State',
  draftVersions: '39_Draft Versions',
  userDecisions: '40_User Decisions',
  intentLog: '41_Intent Log',
  assetBinding: '42_Asset Binding',
  visualJobs: '43_Visual Jobs',
  visualVersions: '44_Visual Versions',
  routerDecisions: '45_Router Decisions',
  clarificationQueue: '46_Clarification Queue',
  campaignLocks: '47_Campaign Locks',
  currentFocus: '48_Current Focus',
  globalCalendarAudit: '49_Global Calendar Audit',
  mediaAvailability: '50_Media Availability',
  mediaFolderMap: '51_Media Folder Map',
  campaignFolderMap: '52_Campaign Folder Map',
  playerFolderMap: '53_Player Folder Map',
  mediaScanLog: '54_Media Scan Log',
  mediaOsReadme: '55_Media OS README'
};

export const HEADERS = {
  [SHEETS.contentCalendar]: ['Content ID','Week','Publish Date','Channel','Format','Content Pillar','Title / Topic','Related Player 1','Related Player 2','Related Event / Match','Asset Folder','Status','Priority','Owner','Caption Status','Edit Status','Design Status','Published Link','Notes','Agent Suggestion'],
  [SHEETS.eventsMatches]: ['Event ID','Type','Date','Time','Venue','Division','Player 1','Player 2','Status','Score / Result','Importance','Story Angle','Asset Folder','Website Link','Telegram Source','Created From','Notes','Next Action'],
  [SHEETS.playersContent]: ['Player ID','Player Name','Division','NTRP','Profile Reel Status','Footage Status','Voice Answer','Subtitles Status','Player Card','Asset Folder','Best Clips','Published Reel','Next Content Idea','Priority','Notes','Last Updated','Country / Language','Agent Suggestion'],
  [SHEETS.assetsLibrary]: ['Asset ID','Asset Type','Related Player','Related Event / Match','Date Captured','Drive Folder / File Link','Hard Drive Backup Path','Usability','Used In','Status','Best For','Caption Notes','Rights / Permission','Notes','Uploaded By','Last Checked'],
  [SHEETS.storylines]: ['Storyline ID','Date Found','Division','Player / Players','Match','Trigger Type','Why It Matters','Suggested Channel','Suggested Format','Status','Related Content ID','Telegram Draft','IG Story Idea','Notes'],
  [SHEETS.templates]: ['Template ID','Template Type','Channel','Use Case','Template Text / Prompt','Variables','Tone','Approval Needed','Status','Notes','Last Updated','Owner'],
  [SHEETS.publishedArchive]: ['Publication ID','Content ID','Published Date','Channel','Format','Title / Topic','Published Link','Related Player','Related Event','Asset Folder','Performance Notes','Views','Likes','Comments','Saves / Shares','Reuse Idea'],
  [SHEETS.partnersScouting]: ['Lead ID','Account / Business','Category','Instagram / Website','Why Relevant','Audience Fit','Collaboration Idea','Priority','Status','Contact Person','Last Contact','Next Action','Notes','Agent Suggestion'],
  [SHEETS.systemLogs]: ['Log ID','Timestamp','Level','Run ID','Agent','Action','Status','Input Summary','Output Summary','Error','Raw JSON'],
  [SHEETS.dedup]: ['Dedup Key','Timestamp','Source','Status','Notes'],
  [SHEETS.feedbackRules]: ['Rule ID','Timestamp','Scope','Rule','Applies To Agent','Source Message','Status','Notes'],
  [SHEETS.projectContext]: ['Context ID','Category','Title','Content','Status','Priority','Last Updated','Source'],
  [SHEETS.brandRulesMemory]: ['Rule ID','Category','Rule','Applies To','Status','Priority','Source','Last Updated'],
  [SHEETS.botMemory]: ['Memory ID','Type','Memory','Applies To','Status','Source','Created At','Notes'],
  [SHEETS.approvedExamples]: ['Example ID','Content Type','Channel','Content','Why Approved','Applies To','Source','Date'],
  [SHEETS.rejectedExamples]: ['Example ID','Content Type','Channel','Content','Why Rejected','Correction','Source','Date'],
  [SHEETS.visualPrompts]: ['Visual ID','Related Event ID','Asset Type','Channel','Use Case','Prompt','Generation Status','Output Link / Path','Size','Priority','Notes','Last Updated'],
  [SHEETS.matchLogSources]: ['Source ID','Source Type','Spreadsheet ID','Sheet Name','Purpose','Status','Last Sync','Notes'],
  [SHEETS.playerMasterSnapshot]: ['Player ID','Player Name','Division','NTRP','Ranking Points','Wins','Losses','Avatar URL','Profile URL','Country / Language','Notes','Last Synced'],
  [SHEETS.matchLogSnapshot]: ['Match ID','Date','Season','Division','Stage','Player 1','Player 2','Score','Winner','Loser','Storyline Flags','Source','Last Synced'],
  [SHEETS.publicationSchedule]: ['Schedule ID','Related Event ID','Publish Date','Publish Time','Channel','Format','Title','Purpose','Overlap Check','Status','Owner','Related Content ID','Notes','Last Updated'],
  [SHEETS.mediaSuggestions]: ['Suggestion ID','Related Event ID','Related Player','Asset Type','Asset Link / Folder','Best For','Priority','Status','Reason','Missing Asset','Notes','Last Updated'],
  [SHEETS.strategicBriefs]: ['Brief ID','Created At','Horizon','Season Stage','Main Goal','Strategic Thesis','Content Priorities','Risks / Avoid','Sponsor/Product Notes','Recommended Mix','Raw JSON'],
  [SHEETS.lifecycleRules]: ['Rule ID','Event Timing','Phase','Minimum Content','Channels','Timing Rules','User Tasks','Post-event Tail','Status','Notes'],
  [SHEETS.userActionTasks]: ['Task ID','Related Event ID','Due Date','Due Time','Task Type','Task','Why Needed','Priority','Status','Owner','Notes','Last Updated'],
  [SHEETS.sponsorIntegrations]: ['Sponsor ID','Sponsor / Partner','Category','Integration Type','Required Mentions','Preferred Channels','Frequency / Window','Status','Contact','Notes','Last Updated'],
  [SHEETS.ecosystemProducts]: ['Product ID','Product Name','Category','What It Does','Audience','Content Angles','Priority','Status','Launch / Promo Window','Notes','Last Updated'],
  [SHEETS.contentMixAudit]: ['Audit ID','Created At','Period','Players %','Matches %','Community %','Sponsors %','Products %','Education %','Recap %','Risk','Recommendation','Raw JSON'],
  [SHEETS.generatedImages]: ['Image ID','Visual ID','Related Event ID','Asset Type','Prompt','Model','Size','Quality','Format','Drive File ID','Drive Link','Status','Error','Created At'],
  [SHEETS.modelConfig]: ['Role','Env Var','Recommended Model','Fallback Model','Purpose','Status','Notes'],
  [SHEETS.approvalQueue]: ['Approval ID','Created At','Related Event ID','Object Type','Object ID','Title','Summary','Status','Priority','Telegram Chat ID','Telegram Message ID','Owner','Notes','Last Updated'],
  [SHEETS.reminders]: ['Reminder ID','Created At','Due Date','Due Time','Timezone','Reminder Type','Related Event ID','Related Object Type','Related Object ID','Title','Message','Status','Repeat Count','Last Sent At','Next Retry At','Telegram Chat ID','Telegram Message ID','Notes'],
  [SHEETS.followupLog]: ['Follow-up ID','Timestamp','Reminder ID','Related Object ID','Action','Old Status','New Status','Telegram Chat ID','Telegram Message ID','Notes','Raw JSON'],
  [SHEETS.telegramMessageLinks]: ['Link ID','Timestamp','Telegram Chat ID','Telegram Message ID','Direction','Related Type','Related ID','Context','Status','Notes'],
  [SHEETS.stylePack]: ['Style ID','Created At','Style Name','Style Type','Prompt Template','Positive Rules','Negative Rules','Reference Asset IDs','Status','Priority','Notes','Last Updated'],
  [SHEETS.referenceAssets]: ['Reference ID','Created At','Source','Telegram Chat ID','Telegram Message ID','Telegram File ID','Drive Link','Reference Type','Related Player','Related Event ID','Status','Notes','Last Updated'],
  [SHEETS.assetUsageHistory]: ['Usage ID','Created At','Asset ID','Reference ID','Related Event ID','Channel','Format','Used In Content ID','Published Date','Reuse Cooldown Days','Reuse Allowed After','Status','Notes'],
  [SHEETS.campaignState]: ['Campaign ID','Created At','Related Event ID','Campaign Name','Stage','Status','Approved Schedule','Approved Visuals','Approved Drafts','Pending Actions','Last Interaction At','Notes','Raw JSON'],
  [SHEETS.draftVersions]: ['Draft ID','Created At','Related Event ID','Related Content ID','Draft Type','Version','Text','Status','Feedback','Telegram Message ID','Notes','Last Updated'],
  [SHEETS.userDecisions]: ['Decision ID','Timestamp','Telegram Chat ID','Telegram Message ID','Related Type','Related ID','Decision','Comment','Status Before','Status After','Raw Text','Raw JSON'],
  [SHEETS.intentLog]: ['Intent ID','Timestamp','Run ID','Raw Text','Detected Intent','Target Type','Target ID','Confidence','Allowed Actions','Forbidden Actions','Needs Clarification','Reason','Raw JSON'],
  [SHEETS.assetBinding]: ['Binding ID','Timestamp','Reference ID','Asset ID','Related Event ID','Related Campaign ID','Role','Related Player','Status','Confidence','Notes','Raw JSON'],
  [SHEETS.visualJobs]: ['Visual Job ID','Timestamp','Related Event ID','Campaign ID','Visual Type','Requested Variants','Status','Reference IDs','Prompt Summary','Generated Count','Approved Option','Last User Feedback','Next Step','Raw JSON'],
  [SHEETS.visualVersions]: ['Version ID','Timestamp','Visual Job ID','Option Number','Visual ID','Image ID','Drive Link','Status','User Feedback','Revision Of','Prompt','Raw JSON'],
  [SHEETS.routerDecisions]: ['Decision ID','Timestamp','Run ID','Raw Text','Intent','Target Campaign','Target Object Type','Target Object ID','Confidence','Decision Reason','Allowed Actions','Forbidden Actions','Pipeline','Raw JSON'],
  [SHEETS.clarificationQueue]: ['Clarification ID','Timestamp','Run ID','Question','Options','Status','Telegram Chat ID','Telegram Message ID','Raw Text','Raw JSON'],
  [SHEETS.campaignLocks]: ['Lock ID','Timestamp','Related Event ID','Campaign ID','Lock Type','Status','Locked Fields','Reason','Created By','Last Updated'],
  [SHEETS.currentFocus]: ['Focus ID','Timestamp','Telegram Chat ID','Related Event ID','Campaign ID','Focus Type','Reason','Status','Last Interaction At','Notes'],
  [SHEETS.globalCalendarAudit]: ['Audit ID','Timestamp','Period','Campaigns Considered','Conflicts','Balance Notes','Recommendations','Raw JSON'],
  [SHEETS.mediaAvailability]: ['Media Check ID','Timestamp','Related Event ID','Campaign ID','Needed Asset Type','Primary Format','Supporting Format','Fallback Format','Search Scope','Availability','Found Links','Status','Notes'],
  [SHEETS.mediaFolderMap]: ['Folder Key','Folder Name','Folder ID','Parent Key','Parent ID','Path','Purpose','Status','Created At','Last Checked','Notes'],
  [SHEETS.campaignFolderMap]: ['Campaign ID','Related Event ID','Campaign Name','Folder ID','Path','Status','Created At','Last Checked','Notes'],
  [SHEETS.playerFolderMap]: ['Player ID','Player Name','Folder ID','Path','Status','Created At','Last Checked','Notes'],
  [SHEETS.mediaScanLog]: ['Scan ID','Timestamp','Drive File ID','File Name','Mime Type','Folder ID','Folder Path','Detected Type','Related Event ID','Related Players','Status','Drive Link','Notes'],
  [SHEETS.mediaOsReadme]: ['Section','Title','Content','Last Updated']
};
